# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('dpi', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('dpi', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=10)),
                ('nombre_de_negocio', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
                ('tamano', models.CharField(choices=[('0', 'cuarto de oficio'), ('1', 'media carta'), ('2', 'carta'), ('3', 'oficio')], default='0', max_length=1)),
                ('tipo_papel', models.CharField(choices=[('0', 'normal'), ('1', 'sensibilizado')], default='0', max_length=1)),
                ('precio_pedido', models.IntegerField()),
                ('estado_pedido', models.BooleanField(default=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('cliente_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcialApp.cliente')),
                ('empleado_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parcialApp.empleado')),
            ],
        ),
    ]
